{
	"version": 1638028437,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/screen-sheet0.png",
		"images/done-sheet0.png",
		"images/back-sheet0.png",
		"images/rnd-sheet0.png",
		"images/eyes-sheet0.png",
		"images/eyes-sheet1.png",
		"images/eyes-sheet2.png",
		"images/nose-sheet0.png",
		"images/mouth-sheet0.png",
		"images/btn-sheet0.png",
		"images/decor-sheet0.png",
		"images/snow.png",
		"images/head-sheet0.png",
		"images/head-sheet1.png",
		"images/head-sheet2.png",
		"images/horns-sheet0.png",
		"images/horns-sheet1.png",
		"images/horns-sheet2.png",
		"images/ears-sheet0.png",
		"images/ears-sheet1.png",
		"images/start-sheet0.png",
		"images/rays-sheet0.png",
		"media/blim.m4a",
		"media/blim.ogg",
		"media/click.m4a",
		"media/click.ogg",
		"media/jingle-bells.m4a",
		"media/jingle-bells.ogg",
		"media/wintery loop.m4a",
		"media/wintery loop.ogg",
		"media/camera_shutter.m4a",
		"media/camera_shutter.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}